general:
  mode: test
  logLevel: INFO

blockchain:
  network: Ethereum
  # nodeEndpoint: https://your-node-url.com
  # gasPriceMultiplier: 1.2

# wallet:
#   encryptedPrivateKey: ENCRYPTED_KEY
#   encryptionPassphrase: PASSPHRASE # Caution: Be very careful with this, consider secure methods

dexes:
  - name: UNISWAPV3
    contract: 0x5678...efgh
    type: 3
    pairs:
      - token0: USDC
        token1: ETH
        pool: 0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640
      - token0: WBTC
        token1: ETH
        pool: 0xCBCdF9626bC03E24f779434178A73a0B4bad62eD
      - token0: DAI
        token1: USDC
        pool: 0x5777d92f208679DB4b9778590Fa3CAB3aC9e2168
      - token0: LINK
        token1: ETH
        pool: 0x5777d92f208679DB4b9778590Fa3CAB3aC9e2168

  - name: UNISWAPV2
    contract: 0x5678...efgh
    type: 2
    pairs:
      - token0: USDC
        token1: ETH
        pool: 0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc
      - token0: WBTC
        token1: ETH
        pool: 0xBb2b8038a1640196FbE3e38816F3e67Cba72D940
      - token0: DAI
        token1: USDC
        pool: 0xAE461cA67B15dc8dc81CE7615e0320dA1A9aB8D5
      - token0: LINK
        token1: ETH
        pool: 0xa2107FA5B38d9bbd2C461D6EDf11B11A50F6b974

  - name: SUSHISWAPV2
    contract: 0x5678...efgh
    type: 2
    pairs:
      - token0: USDC
        token1: ETH
        pool: 0x397FF1542f962076d0BFE58eA045FfA2d347ACa0
      - token0: WBTC
        token1: ETH
        pool: 0xCEfF51756c56CeFFCA006cD410B03FFC46dd3a58
      - token0: DAI
        token1: USDC
        pool: 0xAaF5110db6e744ff70fB339DE037B990A20bdace
      - token0: LINK
        token1: ETH
        pool: 0xC40D16476380e4037e6b1A2594cAF6a6cc8Da967

  # - name: PANCAKESWAPV3
  #   contract: 0x5678...efgh
  #   type: 3
  #   pairs:
  #     - token0: USDC
  #       token1: ETH
  #       pool: 0x1ac1A8FEaAEa1900C4166dEeed0C11cC10669D36
  #     - token0: WBTC
  #       token1: ETH
  #       pool: 0x9b5699D18DFF51fc65fB8ad6F70d93287C36349f
  #     - token0: DAI
  #       token1: USDC
  #       pool: 0xD9e497BD8f491fE163b42A62c296FB54CaEA74B7
  #     - token0: LINK
  #       token1: ETH
  #       pool: 0x7ca3EdB2c8fb3e657E282e67F4008d658aA161D2

  # - name: BANCOR
  #   contractAddress: 0x5678...efgh
  #   pools:
  #     - token0: USDC
  #       token1: USDC
  #       pool: 0123JE
  #     - token0: DAI
  #       token1: DAI
  #       pool: 0123JE

  # - name: PANCAKESWAP
  #   contractAddress: 0x5678...efgh
  #   pools:
  #     - token0: USDC
  #       token1: USDC
  #       pool: 0123JE
  #     - token0: DAI
  #       token1: DAI
  #       pool: 0123JE

  # - name: FRAXSWAP
  #   contractAddress: 0x5678...efgh
  #   pools:
  #     - token0: USDC
  #       token1: USDC
  #       pool: 0123JE
  #     - token0: DAI
  #       token1: DAI
  #       pool: 0123JE

  # - name: THORCHAIN
  #   contractAddress: 0x5678...efgh
  #   pools:
  #     - token0: USDC
  #       token1: USDC
  #       pool: 0123JE
  #     - token0: DAI
  #       token1: DAI
  #       pool: 0123JE

  # - name: SHIBASWAP
  #   contractAddress: 0x5678...efgh
  #   pools:
  #     - token0: USDC
  #       token1: USDC
  #       pool: 0123JE
  #     - token0: DAI
  #       token1: DAI
  #       pool: 0123JE

tokens:
  - name: USDT
    address: 0xdAC17F958D2ee523a2206206994597C13D831ec7
    decimals: 6
  - name: USDC
    address: 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
    decimals: 6
  - name: DAI
    address: 0x6B175474E89094C44Da98b954EedeAC495271d0F
    decimals: 18
  - name: WBTC
    address: 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
    decimals: 8
  - name: UNI
    address: 0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984
    decimals: 18
  - name: ETH
    address: 0x0
    decimals: 18
  - name: LINK
    address: 0x514910771AF9Ca656af840dff83E8264EcF986CA
    decimals: 18

allowedpairs:
  - token0: USDC
    token1: ETH
  - token0: WBTC
    token1: ETH
  - token0: DAI
    token1: USDC
  - token0: LINK
    token1: ETH
# arbitrage:
#   profitThreshold: 0.01
#   timeLimit: 60
#   maxGasUsage: 200000

# slippage:
#   tolerance: 0.01

# fees:
#   dex1: 0.003
#   dex2: 0.002

# influxDB:
#   endpoint: http://localhost:8086
#   username: your_influxdb_username
#   password: your_influxdb_password

# grafana:
#   endpoint: http://localhost:3000

# alerts:
#   alertThreshold: 0.1
#   notificationMethod: email
