general:
  mode: test
  logLevel: INFO

blockchain:
  network: Ethereum

tokens:
  - name: USDT
    address: 0xdAC17F958D2ee523a2206206994597C13D831ec7
    decimals: 6
  - name: USDC
    address: 0xA0b86991c6218b36c1d19D4a2e9Eb0cE3606eB48
    decimals: 6
  - name: DAI
    address: 0x6B175474E89094C44Da98b954EedeAC495271d0F
    decimals: 18
  - name: WBTC
    address: 0x2260FAC5E5542a773Aa44fBCfeDf7C193bc2C599
    decimals: 8
  - name: UNI
    address: 0x1f9840a85d5aF5bf1D1762F925BDADdC4201F984
    decimals: 18
  - name: WETH
    address: 0x0
    decimals: 18
  - name: LINK
    address: 0x514910771AF9Ca656af840dff83E8264EcF986CA
    decimals: 18

pairs:
  - token0: USDC
    token1: WETH
    decimals0: 6
    decimals1: 18
    pools:
      - protocol: UNISWAPV3
        address: 0x88e6A0c2dDD26FEEb64F039a2c41296FcB3f5640
        type: 1
      - protocol: UNISWAPV2
        address: 0xB4e16d0168e52d35CaCD2c6185b44281Ec28C9Dc
        type: 2
      - protocol: SUSHISWAPV2
        address: 0x397FF1542f962076d0BFE58eA045FfA2d347ACa0
        type: 2
  - token0: WBTC
    token1: WETH
    decimals0: 8
    decimals1: 18
    pools:
      - protocol: UNISWAPV3
        address: 0xCBCdF9626bC03E24f779434178A73a0B4bad62eD
        type: 1
      - protocol: UNISWAPV2
        address: 0xBb2b8038a1640196FbE3e38816F3e67Cba72D940
        type: 2
      - protocol: SUSHISWAPV2
        address: 0xCEfF51756c56CeFFCA006cD410B03FFC46dd3a58
        type: 2
  - token0: DAI
    token1: USDC
    decimals0: 18
    decimals1: 6
    pools:
      - protocol: UNISWAPV3
        address: 0x5777d92f208679DB4b9778590Fa3CAB3aC9e2168
        type: 1
      - protocol: UNISWAPV2
        address: 0xAE461cA67B15dc8dc81CE7615e0320dA1A9aB8D5
        type: 2
      - protocol: SUSHISWAPV2
        address: 0xAaF5110db6e744ff70fB339DE037B990A20bdace
        type: 2
  - token0: LINK
    token1: WETH
    decimals0: 18
    decimals1: 18
    pools:
      - protocol: UNISWAPV3
        address: 0x5777d92f208679DB4b9778590Fa3CAB3aC9e2168
        type: 1
      - protocol: UNISWAPV2
        address: 0xa2107FA5B38d9bbd2C461D6EDf11B11A50F6b974
        type: 2
      - protocol: SUSHISWAPV2
        address: 0xC40D16476380e4037e6b1A2594cAF6a6cc8Da967
        type: 2
